version: "2"
services:
   namenode:
      image: apache/hadoop:3.4.1
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
        - 9000:9000
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      volumes:
        - ./data:/data
   datanode:
      image: apache/hadoop:3.4.1
      command: ["hdfs", "datanode"]
      env_file:
        - ./config      
   resourcemanager:
      image: apache/hadoop:3.4.1
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
   nodemanager:
      image: apache/hadoop:3.4.1
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config